<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Adresse extends \Entity\Adresse implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function setRue($rue)
    {
        $this->__load();
        return parent::setRue($rue);
    }

    public function getRue()
    {
        $this->__load();
        return parent::getRue();
    }

    public function setCite($cite)
    {
        $this->__load();
        return parent::setCite($cite);
    }

    public function getCite()
    {
        $this->__load();
        return parent::getCite();
    }

    public function setLocalite(\Entity\Localite $localite = NULL)
    {
        $this->__load();
        return parent::setLocalite($localite);
    }

    public function getLocalite()
    {
        $this->__load();
        return parent::getLocalite();
    }

    public function setPharmacie(\Entity\Pharmacie $pharmacie = NULL)
    {
        $this->__load();
        return parent::setPharmacie($pharmacie);
    }

    public function getPharmacie()
    {
        $this->__load();
        return parent::getPharmacie();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numero', 'rue', 'cite', 'localite', 'pharmacie');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}