<?php

namespace Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoordonneeGPS
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneeGPS extends EntityRepository
{
}